ElectronicQueue/Controllers/AuthorizationController.cs
using System.Web.Mvc;
using System.Web.Security;
using ElectronicQueue.Models;

namespace ElectronicQueue.Controllers
{
    [AllowAnonymous]
    public class AuthorizationController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel loginInfo, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(loginInfo.Login, loginInfo.Password))
                {
                    FormsAuthentication.SetAuthCookie(loginInfo.Login, loginInfo.RememberMe);
                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", "Неправильный пароль или логин");
            }



            return View("Index");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

ElectronicQueue/Controllers/ControlPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ElectronicQueue.BL.Repositories;
using ElectronicQueue.Data.Entities;

namespace ElectronicQueue.Controllers
{
    [Authorize(Roles = "admin")]
    public class ControlPanelController : Controller
    {
        private readonly ISpecialtyRepository _specialtyRepository;
        private readonly ILectureHallRepository _lectureHallRepository;
        private readonly IUserRepository _userRepository;

        public ControlPanelController(ISpecialtyRepository specialtyRepository, ILectureHallRepository lectureHallRepository, IUserRepository userRepository)
        {
            _specialtyRepository = specialtyRepository;
            _lectureHallRepository = lectureHallRepository;
            _userRepository = userRepository;
        }

        private void GetViewBagData()
        {
            ViewBag.LectureHallTables = _lectureHallRepository.GetAll();

            List<LectureHall> lectureHalls = _lectureHallRepository.GetLectureHalls();
            ViewBag.LectureHalls = lectureHalls.Select(x => new SelectListItem {Text = x.Name, Value = x.LectureHallId.ToString()});

            List<Specialty> specialties = _specialtyRepository.GetAll();
            ViewBag.Specialties = specialties.Select(x => new SelectListItem { Text = x.Name, Value = x.SpecialtyId.ToString() });

            List<User> teachers = _userRepository.GetTeachers();
            ViewBag.Teachers = teachers.Select(x => new SelectListItem() {Text = x.Login, Value = x.UserId.ToString()});

            ViewBag.Users = _userRepository.GetUsers();

        }
        public ActionResult Index()
        {
            GetViewBagData();
            return View(_specialtyRepository.GetSpecialtiesForControlPanel());
        }

        public ActionResult Delete(string guid)
        {
            _specialtyRepository.Delete(guid);
            _specialtyRepository.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Add(string name, string teacher, bool isPrior)
        {
            if (string.IsNullOrEmpty(name))
                return RedirectToAction("Index");
            _specialtyRepository.Add(name, isPrior, teacher);
            _specialtyRepository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ChangeSpecialty(string id, string name, string userId)
        {
            _specialtyRepository.ChangeSpecialty(id, name, userId);
            _specialtyRepository.SaveChanges();
            return RedirectToAction("Index");
        }

        public void ChangeLectureHall(string id, int? lectureHallId, string specialtyId)
        {
            _lectureHallRepository.ChangeLectureHall(Guid.Parse(id), lectureHallId, Guid.Parse(specialtyId));
            _lectureHallRepository.SaveChanges();

        }

        [HttpPost]
        public ActionResult AddLectureHallTable(string name, int lectureHallId, string specialtyId)
        {
            _lectureHallRepository.AddLectureHallTable(name, lectureHallId, Guid.Parse(specialtyId));
            _lectureHallRepository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteLectureTable(string guid)
        {
            _lectureHallRepository.DeleteTable(Guid.Parse(guid));
            _lectureHallRepository.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteUser(string guid)
        {
            _userRepository.DeleteUser(Guid.Parse(guid));
            _userRepository.SaveChanges();
            return RedirectToAction("Index");
        }

        public string AddUser(User user)
        {
            try
            {
                if (string.IsNullOrEmpty(user.Login) || string.IsNullOrEmpty(user.Password))
                    throw new Exception("Логин и пароль обязательны для заполнения");
                _userRepository.AddUser(user);
                _userRepository.SaveChanges();
                return string.Empty;
            }
            catch (Exception e)
            {
                Response.StatusCode = 404;
                return e.Message;
            }
            
            
        }
    }
}

ElectronicQueue/Controllers/DisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ElectronicQueue.BL.Enums;
using ElectronicQueue.BL.Models;
using ElectronicQueue.BL.Repositories;
using ElectronicQueue.Data.Entities;

namespace ElectronicQueue.Controllers
{
    public class DisplayController : Controller
    {
        private readonly IRequestRepository _requestRepository;

        public DisplayController(IRequestRepository requestRepository)
        {
            _requestRepository = requestRepository;
        }

        public ActionResult Index()
        {
            List<RequestViewModel> requests = _requestRepository.GetRequests();
            if (!User.IsInRole("admin"))
                requests = requests.Where(x => x.StepId == RequestStep.New).ToList();
            return View(requests);
        }

        [Authorize(Roles = "admin")]
        public ActionResult DeleteRequest(string requestId)
        {
            _requestRepository.DeleteRequest(Guid.Parse(requestId));
            _requestRepository.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ElectronicQueue/Controllers/ReceptionController.cs
using System;
using System.Web.Mvc;
using ElectronicQueue.BL.Models;
using ElectronicQueue.BL.Repositories;

namespace ElectronicQueue.Controllers
{
    [Authorize(Roles = "teacher")]
    public class ReceptionController : Controller
    {
        private readonly IRequestRepository _requestRepository;
        private readonly ISpecialtyRepository _specialtyRepository;

        public ReceptionController(IRequestRepository requestRepository, ISpecialtyRepository specialtyRepository)
        {
            _requestRepository = requestRepository;
            _specialtyRepository = specialtyRepository;
        }

        public ActionResult Index()
        {
            ViewBag.SpecialtyNames = _specialtyRepository.GetSpecialtyNames(User.Identity.Name);
            return View();
        }

        [HttpPost]
        public ActionResult InviteEnrollee(bool isChecked)
        {
            try
            {
                string userName = User.Identity.Name;
                EnrolleeViewModel request = _requestRepository.GetTopRequest(userName, isChecked);
                
                return Json(request);
            }
            catch (Exception e)
            {
                Response.StatusCode = 404;
                return Json(new { isError = true, error = e.Message });
            }
            
        }

        public ActionResult ApplyRequest(int requestNumber, bool isClosed)
        {
            _requestRepository.ApplyRequest(requestNumber, isClosed);
            _requestRepository.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ElectronicQueue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <title>Электронная очередь</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Электронная очередь поступления", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Дисплей", "Index", "Display")</li>
                        if (User.IsInRole("teacher"))
                         {
                             <li>@Html.ActionLink("Прием", "Index", "Reception")</li>
                        }

                        if (User.IsInRole("operator"))
                        {
                            <li>@Html.ActionLink("Регистрация абитуриента", "Index", "EnrolleeRegistration")</li>
                        }

                        if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("Панель управления", "Index", "ControlPanel")</li>
                        }

                        <li>@Html.ActionLink("Выйти", "Logout", "Authorization")</li>
                       
                    }
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    
    
    @Scripts.Render("~/bundles/bootstrap")
   
    @RenderSection("scripts", required: false)
</body>
</html>